### ISSUE TITLE
multiple device support

### ISSUE THREAD

**Issue by a5m0** [vvviperrr/SimpleRT#10]
I see in iface_up.sh that the host and device addresses are "hardcoded in android part" so how do we get multiple devices working with this? Thanks!

**Comment by vvviperrr** [comment]
Right now only 1 device supported. It can be modified to work with multiple devices (btw im working on it, but development is pretty slow, as i working only in my free time).

**Comment by vvviperrr** [comment]
If u want to help with multiple device impl, feel free to contact with me in skype: vvviperrr00

**Comment by vvviperrr** [comment]
in progress

**Comment by vvviperrr** [comment]
done!

https://github.com/vvviperrr/SimpleRT/tree/multi_tether

**Comment by darcykimball** [comment]
The multi_tether branch link is broken; would you be able to reupload it?

**Comment by vvviperrr** [comment]
yep :)
