### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by AlphaOmega3** [vvviperrr/SimpleRT#11]
Hi! It's possible add an ability to work with Orbot/I2P networks??

**Comment by vvviperrr** [comment]
hi. unfortunately, android support only 1 vpn connection peer time, which is already used by simplert. u have to configure tor/i2p connection on PC side and route simplert traffic here.

**Comment by AlphaOmega3** [comment]
Wait, in the case of Orbot, I do not use VPN, but I directly set access to the root

**Comment by vvviperrr** [comment]
>in the case of Orbot, I do not use VPN

then everything should work

**Comment by AlphaOmega3** [comment]
But once the boot is always in search of the connection. for what I thought it was the app that do not would support. at this point I will try to review the Orbot settings. I thank you anyway for your time

**Comment by vvviperrr** [comment]
>Issues: Some apps do not recognize the reverse tethered internet connection due to ConnectivityManager policy. Just leave WiFi or 3g connection active, connection will go through SimpleRT anyway.

nothing can be done with this without root access.
