### ISSUE TITLE
Is there any way to share the Reverse tethered internet through Mobile Wifi Hotspot?

### ISSUE THREAD

**Issue by didium** [vvviperrr/SimpleRT#14]
When i tried this, i couldn't get internet on the second device which is connected to this SimpleRt device through Wifi Hotspot.

Any idea how to achieve this?

**Comment by vvviperrr** [comment]
impossible without root access on device. even with root access, it depends.

**Comment by didium** [comment]
Tried with bluetooth Internet sharing too.. Didn't work

**Comment by vvviperrr** [comment]
It's android platform issue. Android does not recognise tunnel interface as "real" network interface.
