### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by plohoyav** [vvviperrr/SimpleRT#16]
I download zip file from this site, extracted it, go to directory simple-rt-cli and run "make" in terminal, then i execute "sudo ./simple-rt" in terminal on my Linux Manjaro computer. I also download apk file and installed it on android tablet. I connect via usb cable android and computer. Web pages did not opens on android.

**Comment by vvviperrr** [comment]
more info needed. what type of android device, version, os, logs, ifconfig, etc.

**Comment by plohoyav** [comment]
1. my android device is Pipo S1 Pro 7" tablet with version android 4.2.2
2. my computer os is Manjaro Linux JWM 16.06.1 with ethernet adapter

**Comment by vvviperrr** [comment]
набери в скайп, vvviperrr00, помогу

**Comment by plohoyav** [comment]
1. FIrst of all, check out iface_up.sh and change LOCAL_INTERFACE, if you need.
Это интерфейс сетевой карты, подключенной к интернет. Правильно?

**Comment by plohoyav** [comment]
2. ####There is already built apk https://github.com/vvviperrr/SimpleRT/releases/download/1.0/simple-rt.apk
Этот файл можно использовать?

**Comment by plohoyav** [comment]
3. run console util as root
┌─[Вт янв 03][user@manjaro:~/Загрузки/SimpleRT-master/simple-rt-cli]
└─> sudo ./simple-rt
libusb callback registered!

Правильно?

**Comment by plohoyav** [comment]
4. Usage:

    run console util as root
    connect your android device

После установки приложения simplert.apk есть кнопка Готово, но нет кнопки Открыть, это нормально?
Запускаю приложение, соединяю планшет и компьютер USB-microUSB кабелем и получаю 2 сообщения на планшете:
а) Отладка по USB разрешена
б) USB-подключение установлено

вижу на компьютере в терминале:
┌─[Вт янв 03][user@manjaro:~/Загрузки/SimpleRT-master/simple-rt-cli]
└─> sudo ./simple-rt
[sudo] пароль для user: 
libusb callback registered!
Kernel driver is active!
Kernel driver detached!
Device 2207:0010 is not support accessory! Reason: Resource busy

**Comment by plohoyav** [comment]
5. First connection requires some trivial steps: 1 2 3

Ни одно из трёх сообщений, изображённых на снимках, не появилось.

**Comment by vvviperrr** [comment]
>Это интерфейс сетевой карты, подключенной к интернет. Правильно?
да
>Этот файл можно использовать?
можно этот, можно установить с f-droid
>Правильно?
да
>После установки приложения simplert.apk есть кнопка Готово, но нет кнопки Открыть, это нормально?
да

>Device 2207:0010 is not support accessory! Reason: Resource busy
либо твоя система перехватила управление устройством (установлен какой-нибудь mtpfs) либо твоя китайчина не поддерживает android accessory. Сложно сказать.

**Comment by vvviperrr** [comment]
кстати, насколько я знаю, в таких китайцах еще и tun модуля нет, который так же нужен утилите. так что тебе проще поднять рута, благо на рокчипе это делается очень просто.

**Comment by plohoyav** [comment]
6. либо твоя система перехватила управление устройством (установлен какой-нибудь mtpfs)

на компьютере ничего содержащего в своём названии mtp не установлено

7. либо твоя китайчина не поддерживает android accessory

если верить https://geektimes.ru/post/119208/ 
Режимы USB хоста и USB устройства поддерживаются начиная с Android 3.1, а у меня 4.2

**Comment by plohoyav** [comment]
8. в таких китайцах еще и tun модуля нет

на странице 
http://www.arctablet.com/blog/forum/pipo-s1-ds733/rom-pipo-s1-pro-smart-s1pro-custom-root-android-4-2-2-firmware-20131213/
написано, что есть tun модуль

**Comment by plohoyav** [comment]
9. проще поднять рута
нужно включить рут перед запуском браузера?

**Comment by vvviperrr** [comment]
>на компьютере ничего содержащего в своём названии mtp не установлено

я сказал для примера, мб что-то еще

>Режимы USB хоста и USB устройства поддерживаются начиная с Android 3.1, а у меня 4.2

я говорю не про режим усб хоста и устройства, а про поддержку android open accessory

>написано, что есть tun модуль

ты дал ссылку на какую-то кастомную прошивку, где написано, что тун есть. что как бы намекает, что в оригинальной заводской его нет. или у тебя именно эта прошивка?

так или иначе, нужно разбираться.

**Comment by vvviperrr** [comment]
вроде бы пофиксил
