### ISSUE TITLE
libusb callback deregistered! / error open tun: Resource busy / tun_alloc failed: Resource busy

### ISSUE THREAD

**Issue by Quenz** [vvviperrr/SimpleRT#17]
Phone is Google Pixel XL, Android 7.1.1. Connected to a MacBook Pro (Retina, 15-inch, Mid 2015), macOS Sierra, 10.12.2, with libusb 1.0.20 from the Homebrew package manager.

"SimepleRT connected!" comes up on my phone when I plug it in, but this comes up in the Terminal:

> sudo ./simple-rt
libusb callback registered!
Kernel driver is not active!
Device supports AOA 2.0!
Sending identification to the device
 sending manufacturer: Konstantin Menyaev
 sending model: SimpleRT
 sending description: Simple Reverse Tethering
 sending version: 1.0
 sending url: https://github.com/vvviperrr/SimpleRT
 sending serial number: j3qq4-h7h2v-2hch4-m3hk8-6m8vw
Turning the device in Accessory mode
Found accessory 18d1:2d01
accessory connected!
libusb callback deregistered!
error open tun: Resource busy
tun_alloc failed: Resource busy

Not sure if USB debugging needs to be enabled, but I tried without and with.

**Comment by vvviperrr** [comment]
there is such problem with google devices (nexus). see other issues. i really dont have any clue with this bug. and dont have any google device to test it. sry.

**Comment by Quenz** [comment]
[TunTap](http://tuntaposx.sourceforge.net/)? I installed that, yes.

**Comment by vvviperrr** [comment]
hi. i just removed osx tuntap dependency, now i use utun module (osx buildin userspace tunnels). Now everything is working fine. btw, u need to update android app too.
