### ISSUE TITLE
[NOT AN ISSUE] AUR package

### ISSUE THREAD

**Issue by AnatolyRugalev** [vvviperrr/SimpleRT#19]
Hi!

I'm tired of making systemd units for simple-rt every time, so I decided to make an AUR package for it. Any Arch Linux user now can easily install it this way:
```
yaourt -S simple-rt
sudo systemctl enable simple-rt
sudo systemctl start simple-rt
```
https://aur.archlinux.org/packages/simple-rt

I had to make dirty hack to replace `eth0` interface name in `iface_up` script, but in my case it works fine. I can add you as co-maintainer if you want so.

Thank you for your work 👍

**Comment by vvviperrr** [comment]
thanks for respond and contributing :)

btw, there is new version, now u can pass interface name in command line.

**Comment by AnatolyRugalev** [comment]
@vvviperrr nice, it's much better now. I updated package already
