### ISSUE TITLE
name of the network interface

### ISSUE THREAD

**Issue by idespisevalvecoders** [vvviperrr/SimpleRT#20]
u think everyone got default name like eth0? may i ask why? in my case its enp0s8 so eth0: error fetching interface information happens

**Comment by vvviperrr** [comment]
>u think everyone got default name like eth0
most users, i suppose

>in my case its enp0s8
check out -i option.

**Comment by idespisevalvecoders** [comment]
desktop side says accessory connected! but nothing works because, wild guess, on the other side usb0 or something takes the spotlight, which i don't have either. netconfig says nothing up.

**Comment by vvviperrr** [comment]
do you installed latest apk (from releases tab)?

>netconfig says nothing up

do you mean netcfg tool on android? it should show tun0 device as up.

can you paste cli tool output after device connected?
"ip a" and "ip r" will be helpful too.

**Comment by idespisevalvecoders** [comment]
i've installed apk. desktop side says:
read_usb_packet failed: Input/Output Error

**Comment by vvviperrr** [comment]
which device do you have?

i cant help you without any logs.

**Comment by idespisevalvecoders** [comment]
it's connected somehow after several tries, but even ping does nothing. don't bother i bridged my ethernet connection with usb tether and it worked.
