### ISSUE TITLE
apk leaves this shit

### ISSUE THREAD

**Issue by idespisevalvecoders** [vvviperrr/SimpleRT#22]
![screenshot_2017-04-06-15-39-19](https://cloud.githubusercontent.com/assets/25696830/24754910/f1b1772e-1ae0-11e7-9cb9-f78588f7297f.png)

**Comment by vvviperrr** [comment]
u still rinning utility on pc side!!!

**Comment by idespisevalvecoders** [comment]
certainly not

**Comment by vvviperrr** [comment]
certainly IT IS! ps aux | grep simple

**Comment by idespisevalvecoders** [comment]
still nothing

**Comment by vvviperrr** [comment]
what nothing? u still running simple-rt. period. there is no miracles. this window ONLY appears, if pc side utility trying to set usb device into accessory mode.

**Comment by vvviperrr** [comment]
[c4690a87](https://github.com/vvviperrr/SimpleRT/commit/c4690a872dc4bb055dc32c69806643f2a79ca55a)
