### ISSUE TITLE
read_usb_packet failed: Input/Output Error

### ISSUE THREAD

**Issue by fervi** [vvviperrr/SimpleRT#23]
Phone: Samsung Galaxy Note 2
OS: Replicant 6.0

Log:
http://meshnet-users.tk/paste/p/ajwo/z.txt

It looks normally, but internet doesn't work

**Comment by vvviperrr** [comment]
looks like some devices have such issue. i dont have any ideas how to fix this. can u run simplert, connect device and copy output of lsusb -vvv? thanks.

**Comment by fervi** [comment]
http://meshnet-users.tk/paste/p/ajwq/f.txt

**Comment by vvviperrr** [comment]
seems like i got it

https://github.com/vvviperrr/SimpleRT/blob/master/simple-rt-cli/src/adk.c#L55

change this constants to:

#define AOA_ACCESSORY_EP_IN         0x82
#define AOA_ACCESSORY_EP_OUT        0x04

recompile and try again.

btw. try firs with google dns (-n param) for clearance

**Comment by fervi** [comment]
Yep it works. Thanks.

If u can, fix something to works automatically without modify.

Thanks again

**Comment by vvviperrr** [comment]
AWESOME :) Thanks for u support.

I will update the code to get this numbers from device.

**Comment by fervi** [comment]
Ofc. it works for me. Maybe for someone else it doesn't work or something like that :P

**Comment by vvviperrr** [comment]
i understand. the problem was in this params, they are hardcoded. i need to read this numbers from user device :)

**Comment by fervi** [comment]
Sorry, now works without mods :+1:
