### ISSUE TITLE
I am having issues compiling it under Lubuntu

### ISSUE THREAD

**Issue by Zero3K** [vvviperrr/SimpleRT#28]
I almost have it compiled, I just have the following errors left to fix:

obj/src/adk.o: In function `get_accessory_endpoints':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:72: undefined reference to `libusb_get_config_descriptor'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:113: undefined reference to `libusb_free_config_descriptor'
obj/src/adk.o: In function `is_accessory_present':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:137: undefined reference to `libusb_get_device_descriptor'
obj/src/adk.o: In function `probe_usb_device':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:159: undefined reference to `libusb_open'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:160: undefined reference to `libusb_strerror'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:169: undefined reference to `libusb_claim_interface'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:171: undefined reference to `libusb_strerror'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:180: undefined reference to `libusb_kernel_driver_active'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:182: undefined reference to `libusb_detach_kernel_driver'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:187: undefined reference to `libusb_strerror'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:195: undefined reference to `libusb_control_transfer'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:284: undefined reference to `libusb_control_transfer'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:301: undefined reference to `libusb_strerror'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:305: undefined reference to `libusb_attach_kernel_driver'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:309: undefined reference to `libusb_close'
obj/src/adk.o: In function `read_usb_packet':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:323: undefined reference to `libusb_bulk_transfer'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:329: undefined reference to `libusb_strerror'
obj/src/adk.o: In function `write_usb_packet':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:350: undefined reference to `libusb_bulk_transfer'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/adk.c:356: undefined reference to `libusb_strerror'
obj/src/accessory.o: In function `free_accessory':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/accessory.c:191: undefined reference to `libusb_release_interface'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/accessory.c:192: undefined reference to `libusb_close'
obj/src/main.o: In function `main':
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:81: undefined reference to `libusb_init'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:96: undefined reference to `libusb_set_debug'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:129: undefined reference to `libusb_hotplug_register_callback'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:141: undefined reference to `libusb_handle_events_completed'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:146: undefined reference to `libusb_hotplug_deregister_callback'
/home/bryan/Desktop/SimpleRT/simple-rt-cli/src/main.c:147: undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'simple-rt' failed
make: *** [simple-rt] Error 1

**Comment by vvviperrr** [comment]
you need to install libusb1-0.0-dev package

**Comment by Zero3K** [comment]
I did install it. It complained of not finding libusb.h until I modified the source code to point to the correct one.

**Comment by vvviperrr** [comment]
because u don't installed pkg-config

**Comment by Zero3K** [comment]
I compiled it and got it running. Now it errors out with "eth0: error fetching interface information: Device not found"

**Comment by vvviperrr** [comment]
u need to pass you network interface via-i option. u can see network interfaces via ip addr command, or ifconfig.

**Comment by Zero3K** [comment]
How about it trying the interfaces with the naming scheme of the one I have? (which is enp0s3).

**Comment by vvviperrr** [comment]
i already  use "default" iface - eth0 for linux, en0 for osx. i will try to support predictable network interface names.
