### ISSUE TITLE
Issue with DirecTV App

### ISSUE THREAD

**Issue by Zero3K** [vvviperrr/SimpleRT#29]
I disabled the Wifi since I am tethered to my PC via a VM (until Windows support is added). When I try running the DirectTV App, it complains that I don't have Internet access even though I do. Also, I cannot access my DVR via it.

**Comment by vvviperrr** [comment]
as readme says:
>Issues: Some apps do not recognize the reverse tethered internet connection due to ConnectivityManager policy. Just leave WiFi or 3g connection active, connection will go through SimpleRT anyway.

there is another ticket - https://github.com/vvviperrr/SimpleRT/issues/3

so this issue will be fixed, but app will be working only on api >= 22.
now, app works on api >=14
