### ISSUE TITLE
Issue with it and Bleach: Brave Souls 

### ISSUE THREAD

**Issue by Zero3K** [vvviperrr/SimpleRT#30]
When I am tethering with it and trying to play the game I mentioned, it complains about network connectivity issues every so often.

**Comment by vvviperrr** [comment]
i already describe this issue in previous ticket

**Comment by Zero3K** [comment]
Its not the same issue since I have enabled Wifi thanks to your suggestion.

**Comment by vvviperrr** [comment]
and what about other apps? google play / youtube?

**Comment by Zero3K** [comment]
Here's the log of the errors in the game that I outputted to a file:

[debug.zip](https://github.com/vvviperrr/SimpleRT/files/991086/debug.zip)

**Comment by Zero3K** [comment]
Tales of the Rays is also complaining about network connectivity issues.

**Comment by vvviperrr** [comment]
test on youtube app. if its not working on pure tethering, but worked, when wifi AND simplert running, then i suppose that everything is working fine. this is impossible without root to do anything else.

**Comment by Zero3K** [comment]
Pure tethering? I just have a tablet, not a phone.

**Comment by vvviperrr** [comment]
i mean, youtube should not work, when only simplert running (without wifi or 3g). but if you enable wifi, connect to ANY network (with or without internet, don't care) and then start simplert - youtube should work fine. this is android platform limitation (at least which api <22)

**Comment by Zero3K** [comment]
Hmm, I'm trying to update Youtube. With Simple-RT and Wifi enabled, its just stuck at Downloading...

**Comment by vvviperrr** [comment]
just update youtube on my device. enable wifi, connect to router, enable simple-rt, run google play, start update. everything is working.

**Comment by Zero3K** [comment]
Can you please try Tales of the Rays/Bleach: Brave Souls to see if you get any errors or not?
