### ISSUE TITLE
Automatic stopping of service when USB cable is unplugged

### ISSUE THREAD

**Issue by Zero3K** [vvviperrr/SimpleRT#31]
It would be nice if it could do that since the other tethering program (gnirehtet) does that.

**Comment by vvviperrr** [comment]
which service? android service? its stopped.

**Comment by Zero3K** [comment]
It is? I don't see any notification of it being stopped.

**Comment by vvviperrr** [comment]
where do you suppose to see it? as soon as key logo in android toolbar disappeared - its stopped

**Comment by Zero3K** [comment]
It doesn't stop when the OS is frozen, etc.

**Comment by vvviperrr** [comment]
i dont understand. what do you mean by "service"? android or desktop part?

**Comment by Zero3K** [comment]
Android service. When I pressed Ctrl+C to close the Desktop Client, the Android Service is still running since the key icon is still being shown. It should notice that the client is no longer connected to it and stop itself when that happens.

**Comment by vvviperrr** [comment]
>When I pressed Ctrl+C to close the Desktop Client, the Android Service is still running since the key icon is still being shown

yes, its true. simplert is made to be daemon style app. right now only correct way to disconnect - just to unplug cable.
