### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by Henningstone** [vvviperrr/SimpleRT#38]
First of all, thanks for you great tool!
I've only got one issue... I only get download speeds of less than 300 KB/s on my phone when connecting it though SimpleRT, although my internet connection can handle up to 2 MB/s.
Am I doing something wrong or is this normal behavior?

I'm using Linux with 4.4.0 kernel on my computer and Android 6.0 on my phone.
I compiled the command line tool myself and used the provided apk.

**Comment by vvviperrr** [comment]
Hi.

No, this is not normal. I have all 40Mbps on my tablet (tested with android speedtest app). Maybe u ISP provider detect tethering and limit speed? u internet connection based on ADSL?

U can do one simple test: set up any server on desktop (samba, ftp, http, whatever), and try to download some file (via es explorer, for example). desktop ip is 10.1.1.1.

**Comment by Henningstone** [comment]
Ok I must apologize for bothering you with this, apparently it was my own fault.
My phone was set to only use 2G connection, not 3G/4G/LTE. Unfortunately it applied this limitation not only to the real mobile data sent over the air, but also to the data over SimpleRT, even when mobile data was off and WLAN was on to trick the NetworkManager.
