### ISSUE TITLE
How much flowrate do you have? why not use wifi directly, hah

### ISSUE THREAD

**Issue by KnightUK** [vvviperrr/SimpleRT#4]

**Comment by vvviperrr** [comment]
>How much flowrate do you have?

about 100 mbit p/s, which is strange, i thought will be much more, maybe i miss something

>why not use wifi directly, hah

it depends) in some situations you cant use wifi/3g - slow speed, always disconnections, no wifi at all, etc. But you have BB with fat bandwith, why dont use it, and btw charge device :)

**Comment by dmitry** [comment]
Not everyone like wireless connections, because of the body safety, data security, link stability and speed.

**Comment by randomstuff** [comment]
I guess using one bulk transfer packet is not very efficient. Modern network USB protocol pack multiple IP packets/Ethernet frames in a single bulk transfer.

**Comment by vvviperrr** [comment]
> I guess using one bulk transfer packet is not very efficient. Modern network USB protocol pack multiple IP packets/Ethernet frames in a single bulk transfer.

agree, current implementation is naive. will be working on it)

**Comment by AnatolyRugalev** [comment]
I use this utility together with [SoundWire](http://georgielabs.net/). This allows to use one pair of headphones with my phone and PC at the same time.
