### ISSUE TITLE
Cant set up Tun Interface

### ISSUE THREAD

**Issue by MordragT** [vvviperrr/SimpleRT#44]
Hello , when i try to start the program i get this error:
[tom@tom-pc simple-rt]$ sudo ./simple-rt -i enp5s0
[sudo] Passwort für tom: 
starting network
configuring:
local interface: enp5s0
virtual interface: tun0
network: 10.1.1.0
address: 10.1.1.1
netmask: 24
nameserver: 8.8.8.8
Error: either "dev" is duplicate, or "10.1.1.1/24" is a garbage.
Unable set iface tun0 up
Unable to start network!

It maybe really easy to fix, but i dont know why it isnt working.

**Comment by vvviperrr** [comment]
hi. please, provide some logs (described on main page)

**Comment by NwawelAIroume** [comment]
this may be because the interface you specified is wrong
