### ISSUE TITLE
How to solve "bulk transfer error: Input/Output Error"?

### ISSUE THREAD

**Issue by dmitry** [vvviperrr/SimpleRT#5]
Once I accept on the android device I get:

```
libusb callback registered!
Device supports AOA 2.0!
Sending identification to the device
...
...
Found accessory 18d1:2d00
accessory connected!
libusb callback deregistered!
net.ipv4.ip_forward = 1
bulk transfer error: Input/Output Error
```

`tun` returns `File descriptor in bad state` and that signs it's ready:

```
cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state
```

Any ideas how to solve issue?

**Comment by vvviperrr** [comment]
>cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state

it's ok, tun dev exists only for ioctl's.

what device do you have? some china manufacturers dont support VpnApi in theirs firmware. Threre is no such checks yet. 

ps. maybe something in dmesg?

**Comment by dmitry** [comment]
Samsung Galaxy S2.

After `bulk transfer error: Input/Output Error` I noticed that logs were written:

```
==> /var/log/syslog <==
Aug  2 13:26:30 dmitry NetworkManager[1182]:    SCPlugin-Ifupdown: devices added (path: /sys/devices/virtual/net/tun0, iface: tun0)
Aug  2 13:26:30 dmitry NetworkManager[1182]:    SCPlugin-Ifupdown: device added (path: /sys/devices/virtual/net/tun0, iface: tun0): no ifupdown configuration found.
Aug  2 13:26:30 dmitry NetworkManager[1182]: <warn> /sys/devices/virtual/net/tun0: couldn't determine device driver; ignoring...
```

**Comment by vvviperrr** [comment]
I'm afraid, i can't help right now, more checks needs to be supported. I'll try do it asap. If you interesting, try it with another device.

**Comment by dmitry** [comment]
@vvviperrr hehe, I don't have other android devices, just that one.

**Comment by vvviperrr** [comment]
https://github.com/meefik/linuxdeploy/issues/74

i suppose u have the same issue.

First of all, check out /dev/net/tun and /dev/tun on DEVICE via adb or terminal app. /dev/tun should be exist.

**Comment by vvviperrr** [comment]
cli and apk updated, with dialog messages on errors and more precisely logs.

**Comment by dmitry** [comment]
Haven't noticed anything new :(

**Comment by vvviperrr** [comment]
ok, run simple-rt with -d param, connect device and store output here

**Comment by dmitry** [comment]
stock firmware

**Comment by vvviperrr** [comment]
really strange. from u previous log seems like everything is fine. maybe -d param can reveal something

**Comment by kocoman1** [comment]
same error for No name 7 inch tablet (debug and lspci)
[rterror.txt](https://github.com/vvviperrr/SimpleRT/files/871451/rterror.txt)
[simplerterr2.txt](https://github.com/vvviperrr/SimpleRT/files/871456/simplerterr2.txt)

thanks

**Comment by vvviperrr** [comment]
kocoman1
thanks for respond.
u have different problem. as i can see in logs, initialization of you device was successfull, but for some reason usb timeout occurs. seem like you device does not respong via accessory protocol.

there is newer version of simplert (checkout multi_tether branch). it is supports timeouts handling. u can try it.

**Comment by kocoman1** [comment]
Hi still same error with multi version, please see log file, thanks
[multierr.txt](https://github.com/vvviperrr/SimpleRT/files/875346/multierr.txt)

**Comment by vvviperrr** [comment]
hi again.

there was one major improvement commited in [0a3ff8a46](https://github.com/vvviperrr/SimpleRT/commit/0a3ff8a46d0264db3978990aaf94062dee720208)

dont really sure, if this will fix you issue, but give it a try.
thanks.

**Comment by kocoman1** [comment]
Hi the cli program now works but the internet connection is not working on the tablet. I am using ubuntu 16

`ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:19:21:e5:c3:b8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.131/24 brd 192.168.3.255 scope global dynamic enp3s0
       valid_lft 83310sec preferred_lft 83310sec
    inet6 fe80::b468:56f3:d6c9:c90c/64 scope link 
       valid_lft forever preferred_lft forever
3: wlp1s6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 00:0d:88:35:b9:54 brd ff:ff:ff:ff:ff:ff
11: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.1.1.1/24 scope global tun0
       valid_lft forever preferred_lft forever
`

`default via 192.168.3.1 dev enp3s0  proto static  metric 100 
10.1.1.0/24 dev tun0  proto kernel  scope link  src 10.1.1.1 
169.254.0.0/16 dev enp3s0  scope link  metric 1000 
192.168.3.0/24 dev enp3s0  proto kernel  scope link  src 192.168.3.131  metric 100 
`

I change the eth0 to enp3s0 in the xxxx.sh file

thanks

**Comment by vvviperrr** [comment]
> I change the eth0 to enp3s0 in the xxxx.sh file

don't do that. check out -i option in cli tool (and -h). or u have old src tree? update master branch.

everything is seems ok from cli side.

**Comment by kocoman1** [comment]
ok its working now thanks I had to set up a dummy access point
