### ISSUE TITLE
SimpleRT icon was not added to my andoid desktop

### ISSUE THREAD

**Issue by slrslr** [vvviperrr/SimpleRT#52]
SimpleRT icon was not added to my andoid desktop once it was installed.
Please see: https://gitlab.com/fdroid/fdroidclient/issues/1701

**Comment by vvviperrr** [comment]
bro, u dont need icon for this app, cause it's a service. just install and run pc tool.

**Comment by slrslr** [comment]
@vvviperrr thank You for letting me know. It may be handy to explain it in the F-droid app description so one knows that there is no user interface and icon and that it is always autorunning on background.

Also the explanation "just install and run pc tool" is very general for me. Is there any tutorial on which application and what are steps to activate in the phone the internet connectivity via USB cable from my computer? It would be ahndy if the app store description also contains this information so even noob knows how to use it.

**Comment by vvviperrr** [comment]
There is readme file, feel free to use it: https://github.com/vvviperrr/SimpleRT/blob/master/README.md.
