### ISSUE TITLE
Can't build source on mac

### ISSUE THREAD

**Issue by alexandrius** [vvviperrr/SimpleRT#6]
Every time I try to make the source I got the error
http://imgur.com/LklkBkF

I tried reinstalling libusb many times with homebrew. Nothing helped

Please help building from source.

**Comment by vvviperrr** [comment]
show, how you install libusb from homebrew please

**Comment by alexandrius** [comment]
brew install libusb
brew instlal libusb-compat

**Comment by alexandrius** [comment]
I don't know what happened. Just re-downloaded source and It worked. Sorry and thanks.

**Comment by vvviperrr** [comment]
>brew instlal libusb-compat

it will install old version of libusb. SimpleRT depends of libusb-1.0.
