### ISSUE TITLE
undefined symbol: libusb_hotplug_register_callback

### ISSUE THREAD

**Issue by vanous** [vvviperrr/SimpleRT#7]
any idea how to fix this?

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ uname -a
Linux tc-vanek 4.7.0-rc7-amd64 #1 SMP Debian 4.7~rc7-1~exp1 (2016-07-14) x86_64 GNU/Linux

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ make
gcc -g -std=c99 -D_DEFAULT_SOURCE -Wall -Iinclude `pkg-config --cflags libusb-1.0` -c src/linux-adk.c -o obj/src/linux-adk.o
gcc -g -std=c99 -D_DEFAULT_SOURCE -Wall -Iinclude `pkg-config --cflags libusb-1.0` -c src/main.c -o obj/src/main.o
gcc -g -std=c99 -D_DEFAULT_SOURCE -Wall -Iinclude `pkg-config --cflags libusb-1.0` -c src/linux/tun.c -o obj/src/linux/tun.o
gcc  obj/src/linux-adk.o  obj/src/main.o  obj/src/linux/tun.o -Wall -lm -lpthread `pkg-config --libs libusb-1.0` -o simple-rt

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ ldd simple-rt 
	linux-vdso.so.1 (0x00007fff451c6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f01058f8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f01056db000)
	libusb-1.0.so.0 => /usr/local/lib/libusb-1.0.so.0 (0x00007f01054cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f010512b000)
	/lib64/ld-linux-x86-64.so.2 (0x000056104cba4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0104f23000)

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ sudo ./simple-rt 
./simple-rt: symbol lookup error: ./simple-rt: undefined symbol: libusb_hotplug_register_callback

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ aptitude show libusb-1.0-0:amd64
Package: libusb-1.0-0                    
Version: 2:1.0.20-1

tried rc version as below (make clean, make, but still the same error).

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ aptitude show libusb-1.0-0
Package: libusb-1.0-0                    
Version: 2:1.0.21~rc1-1

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ aptitude show libusb-1.0-0-dev
Package: libusb-1.0-0-dev                
Version: 2:1.0.21~rc1-1

**Comment by vanous** [comment]
fixed! seems to be caused by old self-compiled libusb, sorry for the noise!

**Comment by vvviperrr** [comment]
no problem)
