### ISSUE TITLE
Device is not support accessory!

### ISSUE THREAD

**Issue by vanous** [vvviperrr/SimpleRT#8]
sorry, new issue :)

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ sudo ./simple-rt -d
debug mode enabled
libusb callback registered!
## [timestamp] [threadID] facility level [function call] <message>

[ 0.001947] [00002b19] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.001959] [00002b19] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.001963] [00002b19] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
[ 4.900710] [00002b1a] libusb: debug [linux_get_device_address] getting address for device: 2-1.2 detached: 0
[ 4.900758] [00002b1a] libusb: debug [linux_get_device_address] scan 2-1.2
[ 4.900913] [00002b1a] libusb: debug [linux_get_device_address] bus=2 dev=16
[ 4.900931] [00002b1a] libusb: debug [udev_hotplug_event] udev hotplug event. action: add.
[ 4.900941] [00002b1a] libusb: debug [linux_enumerate_device] busnum 2 devaddr 16 session_id 528
[ 4.900967] [00002b1a] libusb: debug [linux_enumerate_device] allocating new device for 2/16 (session 528)
[ 4.901085] [00002b1a] libusb: debug [linux_get_parent_info] Dev 0x7f08200015b0 (2-1.2) has parent 0x7814f0 (2-1) port 2
[ 4.902078] [00002b19] libusb: debug [handle_events] poll() returned 1
[ 4.902111] [00002b19] libusb: debug [handle_events] caught a fish on the event pipe
[ 4.902123] [00002b19] libusb: debug [handle_events] hotplug message received
[ 4.902151] [00002b19] libusb: debug [libusb_get_device_descriptor] 
[ 4.902171] [00002b19] libusb: debug [libusb_get_device_list] 
[ 4.902190] [00002b19] libusb: debug [discovered_devs_append] need to increase capacity
[ 4.902211] [00002b19] libusb: debug [libusb_get_device_descriptor] 
[ 4.902223] [00002b19] libusb: debug [libusb_open] open 2.16
[ 4.902293] [00002b19] libusb: debug [usbi_add_pollfd] add fd 9 events 4
Device is not support accessory!
[ 4.902331] [00002b19] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
[ 4.902353] [00002b19] libusb: debug [handle_events] poll() returned 1
[ 4.902366] [00002b19] libusb: debug [handle_events] caught a fish on the event pipe
[ 4.902379] [00002b19] libusb: debug [handle_events] someone updated the poll fds
[ 5.902537] [00002b19] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 5.902591] [00002b19] libusb: debug [handle_events] poll fds modified, reallocating
[ 5.902622] [00002b19] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[65.905962] [00002b19] libusb: debug [handle_events] poll() returned 0
[66.906124] [00002b19] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[66.906158] [00002b19] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms

on the device:
your released provided apk is installed. it is nexus 5 , Android M: 6.0.1 ,  security patch level August 5th 2016.

No message on the phone at all.

thank you!

**Comment by vvviperrr** [comment]
yeap, this kind a possible bug. i used hardcoded accessory usb endpoint, but on some devices it differs. will try to fix this asap.

**Comment by vanous** [comment]
thank you very much. please compile apk too, if possible. i can then test it for you too :)

**Comment by vvviperrr** [comment]
more precisely output added. can you please provide full debug log?

**Comment by vanous** [comment]
thank you, below is the log:

(i have tried all possible (offered by system) USB settings (Use USB for... Charging|File transfers|Photo transfer (PTP)|MIDI)
P.

vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ sudo ./simple-rt 
libusb callback registered!
Device 18d1:4ee1 is not support accessory! Reason: Resource busy
^C
vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ sudo ./simple-rt -d
debug mode enabled
libusb callback registered!
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.003163] [0000052f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.003189] [0000052f] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.003201] [0000052f] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
[ 3.665730] [00000530] libusb: debug [linux_get_device_address] getting address for device: 2-1.2 detached: 1
[ 3.665752] [00000530] libusb: debug [udev_hotplug_event] udev hotplug event. action: remove.
[ 3.666136] [0000052f] libusb: debug [handle_events] poll() returned 1
[ 3.666146] [0000052f] libusb: debug [handle_events] caught a fish on the event pipe
[ 3.666150] [0000052f] libusb: debug [handle_events] hotplug message received
[ 3.666158] [0000052f] libusb: debug [libusb_unref_device] destroy device 2.28
[ 3.666167] [0000052f] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
[ 3.666172] [0000052f] libusb: debug [handle_events] poll() returned 0
[ 4.666294] [0000052f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 4.666353] [0000052f] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
[ 6.769147] [00000530] libusb: debug [linux_get_device_address] getting address for device: 2-1.2 detached: 0
[ 6.769190] [00000530] libusb: debug [linux_get_device_address] scan 2-1.2
[ 6.769320] [00000530] libusb: debug [linux_get_device_address] bus=2 dev=29
[ 6.769334] [00000530] libusb: debug [udev_hotplug_event] udev hotplug event. action: add.
[ 6.769342] [00000530] libusb: debug [linux_enumerate_device] busnum 2 devaddr 29 session_id 541
[ 6.769352] [00000530] libusb: debug [linux_enumerate_device] allocating new device for 2/29 (session 541)
[ 6.769423] [00000530] libusb: debug [linux_get_parent_info] Dev 0x7fb8ec002160 (2-1.2) has parent 0x9e4600 (2-1) port 2
[ 6.769453] [0000052f] libusb: debug [handle_events] poll() returned 1
[ 6.769475] [0000052f] libusb: debug [handle_events] caught a fish on the event pipe
[ 6.769486] [0000052f] libusb: debug [handle_events] hotplug message received
[ 6.769506] [0000052f] libusb: debug [libusb_get_device_descriptor] 
[ 6.769522] [0000052f] libusb: debug [libusb_get_device_list] 
[ 6.769545] [0000052f] libusb: debug [discovered_devs_append] need to increase capacity
[ 6.769561] [0000052f] libusb: debug [libusb_get_device_descriptor] 
[ 6.769571] [0000052f] libusb: debug [libusb_open] open 2.29
[ 6.769624] [0000052f] libusb: debug [usbi_add_pollfd] add fd 9 events 4
Device 18d1:4ee1 is not support accessory! Reason: Resource busy
[ 6.769663] [0000052f] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
[ 6.769673] [0000052f] libusb: debug [handle_events] poll() returned 1
[ 6.769681] [0000052f] libusb: debug [handle_events] caught a fish on the event pipe
[ 6.769687] [0000052f] libusb: debug [handle_events] someone updated the poll fds
[ 7.769839] [0000052f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 7.769891] [0000052f] libusb: debug [handle_events] poll fds modified, reallocating
[ 7.769920] [0000052f] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
^C

**Comment by vvviperrr** [comment]
seems like some software in your system already grabbed your device (some kind of mtpfs maybe, or adb).  there is api in libusb which can determine such situations, but i need time to figure out. if it possible, you can try to run it on another machine.

btw

> (i have tried all possible (offered by system) USB settings (Use USB for... Charging|File transfers|Photo transfer (PTP)|MIDI)

no need at all. any mode is ok for accessory.

**Comment by vanous** [comment]
OK, will try tomorrow.

**Comment by vanous** [comment]
Sorry, don't have another computer to try this on, but i tried to quit gnome-shell and used simple IceWM manager. However, still the same issue. This being on Debian, i looked and don't have mtpfs nor jmtpfs installed (FUSE and libmtp-based filesystem for accessing MTP). Not sure what i can check next... installing python-usb to see if i can list programs using usb devices...

**Comment by vvviperrr** [comment]
commited, maybe it help.

**Comment by vanous** [comment]
Thank you, no help yet, but new message: Kernel driver is not active!

see full log below.
 
vanous@tc-vanek:/tmp/SimpleRT/simple-rt-cli$ sudo ./simple-rt -d
debug mode enabled
libusb callback registered!
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.009128] [0000257d] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.009176] [0000257d] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.009205] [0000257d] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
[ 2.648270] [0000257e] libusb: debug [linux_get_device_address] getting address for device: 2-1.2 detached: 1
[ 2.648291] [0000257e] libusb: debug [udev_hotplug_event] udev hotplug event. action: remove.
[ 2.648307] [0000257d] libusb: debug [handle_events] poll() returned 1
[ 2.648317] [0000257d] libusb: debug [handle_events] caught a fish on the event pipe
[ 2.648321] [0000257d] libusb: debug [handle_events] hotplug message received
[ 2.648328] [0000257d] libusb: debug [libusb_unref_device] destroy device 2.53
[ 2.648337] [0000257d] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
[ 2.648342] [0000257d] libusb: debug [handle_events] poll() returned 0
[ 3.648456] [0000257d] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 3.648496] [0000257d] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
[ 8.521988] [0000257e] libusb: debug [linux_get_device_address] getting address for device: 2-1.2 detached: 0
[ 8.522052] [0000257e] libusb: debug [linux_get_device_address] scan 2-1.2
[ 8.522202] [0000257e] libusb: debug [linux_get_device_address] bus=2 dev=55
[ 8.522218] [0000257e] libusb: debug [udev_hotplug_event] udev hotplug event. action: add.
[ 8.522229] [0000257e] libusb: debug [linux_enumerate_device] busnum 2 devaddr 55 session_id 567
[ 8.522241] [0000257e] libusb: debug [linux_enumerate_device] allocating new device for 2/55 (session 567)
[ 8.522339] [0000257e] libusb: debug [linux_get_parent_info] Dev 0x7f994c002160 (2-1.2) has parent 0x19ed600 (2-1) port 2
[ 8.522411] [0000257d] libusb: debug [handle_events] poll() returned 1
[ 8.522433] [0000257d] libusb: debug [handle_events] caught a fish on the event pipe
[ 8.522443] [0000257d] libusb: debug [handle_events] hotplug message received
[ 8.522465] [0000257d] libusb: debug [libusb_get_device_descriptor] 
[ 8.522483] [0000257d] libusb: debug [libusb_get_device_list] 
[ 8.522503] [0000257d] libusb: debug [discovered_devs_append] need to increase capacity
[ 8.522527] [0000257d] libusb: debug [libusb_get_device_descriptor] 
[ 8.522536] [0000257d] libusb: debug [libusb_open] open 2.55
[ 8.522587] [0000257d] libusb: debug [usbi_add_pollfd] add fd 9 events 4
[ 8.522605] [0000257d] libusb: debug [libusb_kernel_driver_active] interface 0
Kernel driver is not active!
Device 18d1:4ee1 is not support accessory! Reason: Resource busy
[ 8.522636] [0000257d] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
[ 8.522645] [0000257d] libusb: debug [handle_events] poll() returned 1
[ 8.522651] [0000257d] libusb: debug [handle_events] caught a fish on the event pipe
[ 8.522656] [0000257d] libusb: debug [handle_events] someone updated the poll fds
[ 9.522823] [0000257d] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 9.522879] [0000257d] libusb: debug [handle_events] poll fds modified, reallocating
[ 9.522928] [0000257d] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms

**Comment by vanous** [comment]
I have tried booting straight into bash (init=/bin/bash on the linux command line) , then modprobe tun and then run ./simple-rt -d , but usb devices don't get autodetected - the ./simple-rt -d initializes but no device comes up , probably some modules are missing for udev or what not...

**Comment by fish47** [comment]
I can reproduce this bug(?). I can turn the device into Accessory Mode with it plugged using the code grabbed from here. Maybe we need a delayed check when USB plug event arrived?
Any test code is welcome.

**Comment by SapienTech** [comment]
having same issue as vanous, any updates on a fix?

**Comment by max600** [comment]
Encountered the same issue with OSX + Odroid C2 (Android 6.0.1).

**Comment by vvviperrr** [comment]
seems like something changed in new androids. my device tell same shit now. ill try to resolve asap.

**Comment by aleksander0m** [comment]
Hey, I skipped the "Resource busy" error by using udev notifications to track device addition and removals; see the GNU/Linux CLI rewrite here: https://github.com/aleksander0m/SimpleRT

**Comment by vvviperrr** [comment]
hope i fixed this issue. sorry for delay :)

**Comment by vanous** [comment]
Finally it's working! thank you!

**Comment by vvviperrr** [comment]
my bad :) really appreciate for patience.
