### ISSUE TITLE
1.0 git tag has a comma in it

### ISSUE THREAD

**Issue by eighthave** [vvviperrr/SimpleRT#9]
The 1.0 release is actually marked 1,0 with a comma instead of a period:
https://github.com/vvviperrr/SimpleRT/releases/tag/1%2C0

That breaks automatic version parsers, like in F-Droid:
https://gitlab.com/fdroid/fdroidserver/issues/198

Could this be retagged with a dot instead of a comma?

**Comment by vvviperrr** [comment]
fixed
